# Generated by Django 5.2.10 on 2026-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_description_subject_icon_subjectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='scratch_card_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
