# Generated by Django 5.2.10 on 2026-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='finance_bg',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_bg/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='library_bg',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_bg/'),
        ),
    ]
