# Generated by Django 5.2.9 on 2025-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/qrcodes/'),
        ),
    ]
