# Generated by Django 5.2.9 on 2026-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube Video URL', null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/gallery/'),
        ),
    ]
