# Generated by Django 5.2.10 on 2026-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_galleryimage_video_url_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='student_name',
        ),
        migrations.AddField(
            model_name='admission',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='parent_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='admission',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
