# Generated by Django 5.2.10 on 2026-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_admission_student_name_admission_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='first_school_leaving_cert',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/certificates/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='nin_image',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/nin/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='admissions/others/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/passports/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='state_of_origin_cert',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/origin/'),
        ),
    ]
