# Generated by Django 5.2.9 on 2025-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#198754', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='navbar_color',
            field=models.CharField(default='#2c3e50', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_color',
            field=models.CharField(default='#34495e', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
