# Generated by Django 5.2.9 on 2025-12-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('value_per_card', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('discount', 'Discount Voucher'), ('fee_waiver', 'Fee Waiver'), ('library_credit', 'Library Credit'), ('exam_credit', 'Exam Credit'), ('reward', 'Reward Points'), ('other', 'Other')], max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True)),
                ('pin', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='scratchcard.scratchcardbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScratchCardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_redeemed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='scratchcard.scratchcard')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
