# Generated by Django 5.2.9 on 2025-12-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbt', '0001_initial'),
        ('students', '0003_student_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_ref', models.CharField(max_length=100, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100)),
                ('paystack_auth_url', models.URLField(blank=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scratch_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='scratchcard.scratchcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratchcard_purchases', to='students.student')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accesses', to='cbt.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_accesses', to='students.student')),
                ('scratch_card_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_accesses', to='scratchcard.scratchcardpurchase')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
