# Generated by Django 5.2.9 on 2025-12-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_description_subject_icon_subjectvideo'),
        ('scratchcard', '0001_initial'),
        ('students', '0003_student_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('scratch_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_access', to='scratchcard.scratchcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_accesses', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_accesses', to='core.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
